import { FoodIngredientUnitEnum } from "../../../typesEnumsInterfaces/foodIngredient";
import { TargetLabelEnum } from "../../../typesEnumsInterfaces/targetLabel";

export const testMealPlanData = [
  {
    packetName: "Paket 1",
    price: 560000,
    foodIngredients: [
      {
        ingredientName: "Beras",
        amount: 20,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.KARBO,
        caloricValue: 100,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
    ],
    targetKarbo: 5.848,
    targetProtein: 1.284,
    targetKalori: 42.21,
  },
  {
    packetName: "Paket 2",
    price: 600000,
    foodIngredients: [
      {
        ingredientName: "Beras",
        amount: 20,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.KARBO,
        caloricValue: 100,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
    ],
    targetKarbo: 52.848,
    targetProtein: 1.284,
    targetKalori: 42.21,
  },
  {
    packetName: "Paket 1",
    price: 560000,
    foodIngredients: [
      {
        ingredientName: "Beras",
        amount: 20,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.KARBO,
        caloricValue: 100,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
    ],
    targetKarbo: 5.848,
    targetProtein: 1.284,
    targetKalori: 42.21,
  },
  {
    packetName: "Paket 1",
    price: 560000,
    foodIngredients: [
      {
        ingredientName: "Beras",
        amount: 20,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.KARBO,
        caloricValue: 100,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
    ],
    targetKarbo: 5.848,
    targetProtein: 11.284,
    targetKalori: 42.21,
  },
  {
    packetName: "Paket 1",
    price: 560000,
    foodIngredients: [
      {
        ingredientName: "Beras",
        amount: 20,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.KARBO,
        caloricValue: 100,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
      {
        ingredientName: "Telur Ayam",
        amount: 2,
        unit: FoodIngredientUnitEnum.KG,
        targetLabel: TargetLabelEnum.PROTEIN,
        caloricValue: 140,
      },
    ],
    targetKarbo: 5.848,
    targetProtein: 1.284,
    targetKalori: 424.21,
  },
];
